### ISSUE TITLE
スラッシュコマンドから party, kaere が使用できない

### ISSUE THREAD

**Issue by m1sk9** [approvers/OreOreBot2#1040]
### バグレポートの提出を行う前に

- [X] すでに[同じバグを報告するIssue](https://github.com/approvers/OreOreBot2/issues?q=)が存在しないか確認しましたか?
- [X] セキュリティーに関する不具合ではありませんか? セキュリティーに関する不具合はIssueで報告せず[適切な方法](https://github.com/approvers/OreOreBot2/security/policy#reporting-a-vulnerability)で報告してください

### バグの詳細

`/party`, `/kaere` という単体のコマンドが存在しないためスラッシュコマンドからParty一葉, Kaere一葉の即時スタートができない.

サブコマンドが妨害している?

### 再現方法

1. サーバー内でスラッシュコマンドのリストを表示させる
2. `party`, `kaere` の単体コマンドは存在しない.

### 期待する動作

問題なく実行できる

### はらちょのバージョン

```Text
v1.46.0
```

### 追加情報

Gyokuon は再生可能

**Comment by m1sk9** [comment]
> Using subcommands or subcommand groups will make your base command unusable. You can't send the base /permissions command as a valid command if you also have /permissions add | remove as subcommands or subcommand groups
https://discord.com/developers/docs/interactions/application-commands#subcommands-and-subcommand-groups

**Comment by MikuroXina** [comment]
開始用のサブコマンドとして `start` などを追加すればよいかと
