### ISSUE TITLE
治安維持機能追加

### ISSUE THREAD

**Issue by raiga0310** [approvers/OreOreBot2#126]
- `!sftu`コマンドの追加
  - このボットによる最新の発言を削除する(直近50件)

コメントを受けて修正、削除通知はひとまずなしにします

**Comment by MikuroXina** [comment]
もう少し仕様を具体的にすると,

- `!stfu` コマンドを追加する
  - そのコマンドが打たれたチャンネル内の, このボットによる最新メッセージを削除する

未解決の問題:
- 古すぎるメッセージの削除をしないように, 一定時間のしきい値を設けるべき?
- 削除されたことを通知することの是非
  - 削除されたことをどこに通知するのか?
  - 削除されたことを通知するメッセージも, この `!stfu` コマンドの削除対象になるのでは?

**Comment by raiga0310** [comment]
流れすぎた前のはらちょの投稿を消すのは違うと思うので、
- 直近50メッセージの中において最新のはらちょの投稿
を削除対象にするがいいかなと思っています50が妥当かどうかは考慮の必要があります
