### ISSUE TITLE
Release CIが落ちる

### ISSUE THREAD

**Issue by mk-el** [approvers/OreOreBot2#140]
**Describe the bug (説明)**

DependabotのパッチPRのみ [Release CI](https://github.com/approvers/OreOreBot2/actions/workflows/release.yml) が失敗するようです。

**To Reproduce (再現方法)**

Dependabotに依存関係のアップデート PRを作成させる

**Expected behavior (期待される動作)**

問題なく成功を渡すようにする

**Screenshots (スクリーンショット)**

![image](https://user-images.githubusercontent.com/82575685/166089426-edddf4c6-47c0-4bab-8d06-9d1a31a65d12.png)

**Additional context (追加情報)**

[Release #40](https://github.com/approvers/OreOreBot2/runs/6237374209?check_suite_focus=true) - release / Releaseのエラーログ

```
This can be caused by:

    * a misconfiguration of the repositoryUrl (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) option
    * the repository being unavailable
    * or missing push permission for the user configured via the Git credentials on your CI environment (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication)

SemanticReleaseError: Cannot push to the Git repository.
    at module.exports (/home/runner/.npm/_npx/cdf31b[77](https://github.com/approvers/OreOreBot2/runs/6237374209?check_suite_focus=true#step:5:77)322f1d44/node_modules/semantic-release/lib/get-error.js:6:10)
    at run (/home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/index.js:98:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/index.js:268:22)
    at async module.exports (/home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/cli.js:55:5) {
  code: 'EGITNOPERMISSION',
  details: '**semantic-release** cannot push the version tag to the branch `main` on the remote Git repository with URL `https://x-access-token:[secure]@github.com/approvers/OreOreBot2`.\n' +
    '\n' +
    'This can be caused by:\n' +
    ' - a misconfiguration of the [repositoryUrl](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) option\n' +
    ' - the repository being unavailable\n' +
    ' - or missing push permission for the user configured via the [Git credentials on your CI environment](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication)',
  semanticRelease: true
}
Error: Process completed with exit code 1.
```

**Comment by MikuroXina** [comment]
dependabot がマージコミットを作成することが原因になってそうなので, こちらでマージボタンを押すようにしてもよいかもしれません.

**Comment by mirror-kt** [comment]
依存関係のパッケージを脆弱性のあるバージョンに自動で更新してしまう可能性があるというセキュリティ上の問題があるため、
- dependabotが作成するPRである
- pull_requestイベントで発火されるworkflowである
場合のsecrets.GITHUB_TOKENはread onlyなscopeしか付いていません。
そのためpushに失敗するようです。

解決策としては、
- 毎回目視で更新後のバージョンに脆弱性がないことを確認したのち、手動でre-runする(re-runした場合write scopeが付きます)
- 脆弱性のリスクを黙認してpull_request_targetイベントを使用する
- permissionを明記することでwriteを与える
- workflow_runを用いて信頼のないコードの実行と信頼されたコードの実行を切り分ける

などが考えられます

**Comment by mirror-kt** [comment]
FYI: https://github.blog/changelog/2021-10-06-github-actions-workflows-triggered-by-dependabot-prs-will-respect-permissions-key-in-workflows/

**Comment by MikuroXina** [comment]
そもそも全ての PR のマージ後に Release CI を実行しています (すべて私の所為です). リリース用の PR をマージしたときのみ Release CI を実行するようにワークフローを見直します.

**Comment by MikuroXina** [comment]
#180, #181 で修正できたと思われるので Close.
