### ISSUE TITLE
feat: 教員の名を変えられるように

### ISSUE THREAD

**Issue by m2en** [approvers/OreOreBot2#150]
### Discussed in https://github.com/approvers/OreOreBot2/discussions/148

<div type='discussions-op-text'>

<sup>Originally posted by **mk-el** April 22, 2022</sup>
タコピー構文に新しくオプションを追加し、教員の名を変えられるようにする。

```
!takipi -c 河上先生　進捗
```

```
河上先生「進捗、出して」
める「わ、わからないっピ…」
```

#111 
オプションの分岐に問題がありそうなので決めたいっピ.....</div>

#109  とは別PRで作業することになったのでDiscussionからIssueで再変換しアサインを再構成します。

**Comment by raiga0310** [comment]
作業元のコードの設計上単引数のみしか対応できていないところに新しくたの機能と重ならないように複数引数の処理を追加するのは色々大変なのでひとまずリファクタリングを待ちます。`takopi.ts`(仮称)ができたらさぎょうさいかいします。
