### ISSUE TITLE
feat: 限界ポイントロールはかわえもんにつけないようにする

### ISSUE THREAD

**Issue by Meru92** [approvers/OreOreBot2#155]
**Describe the solution you'd like (要望の内容)**

当初のIssue #47 に **(限界ポイントロールのみはキャンセル)** という注意事項があったにも関わらず現行のはらちょは限界ポイントロールを普通に付与してしまう。

機能の存在からしてつけることは別に間違えたことではないが、限界ポイントをそんなに所持していないのにロールを付与されてしまうのは流石に可哀想なのでかわえもんに同情してそもそもはらちょがつけないようにしたい

上記理由により、新規ロール名に `限界ポイント` という文字列が含まれていたらかわえもんにつけないようにする

**Additional context (追加情報)**

限界ポイントロールは以下のようなものを指す

![image](https://user-images.githubusercontent.com/82575685/166143523-148d8cf7-95a8-4369-b365-100b0a2e24d7.png)

**Comment by mk-el** [comment]
Discordの仕様上、新しいロールはすべて `new role` か `新しいロール` になるため、実装が困難だと判断しました。
クローズとします。

**Comment by mk-el** [comment]
ロール更新見ればいいや、やります

**Comment by Meru92** [comment]
#234
