### ISSUE TITLE
時報システムの復活

### ISSUE THREAD

**Issue by m2en** [approvers/OreOreBot2#17]

**Comment by m2en** [comment]
一定の人気があった機能なので復活させたいと思います

**Comment by MikuroXina** [comment]
元の艦これのもののままだと面白くないしうるさいだけなので, 新しい時報システムは以下のような感じにしてみたいです.

- メンバーの生活サイクルの節目 (起床時間, 就寝時間など) を狙って, 日本の TZ で時報を送る
- 基本的に `#無法地帯` に送信するが, 設定で送信先チャンネルを変えられるようにする
- hibikiness を高めつつ時候やサーバーの雰囲気に合わせたセリフにする

**Comment by m2en** [comment]
***hibikiness***
