### ISSUE TITLE
feat: アスタリスクが入ったファイル名を拒否する

### ISSUE THREAD

**Issue by KisaragiEffective** [approvers/OreOreBot2#185]
### Describe the solution you'd like (要望の内容)
* GitHub Actionsでアスタリスクが入ったファイルが作成されたときRequest Changeする
  * Windowsでは正常に取り扱えない
### Describe alternatives you've considered (代替え案)
* 多分ない

### Additional context (追加情報)
* #184 
* https://stackoverflow.com/questions/26780189/cant-clone-git-repo-on-windows-when-some-file-names-contain-asterisk

**Comment by KisaragiEffective** [comment]
実装方針
* `git --list-changed | grep -Ec '^.*\*.*$'`
* if does not match, exit
* use `andrewmusgrave/automatic-pull-request-review@0.0.5` and REQUEST_CHANGES

**Comment by KisaragiEffective** [comment]
現在においてのアーキテクチャ的な問題などによるリリースの支障ではないためP0を解除

**Comment by KisaragiEffective** [comment]
> 現在においてのアーキテクチャ的な問題などによるリリースの支障ではないためP0を解除

@m2en 現状では非Windowsユーザーが気をつければいいという話にとどまっているので`priority:Critical`は不適当だと考える。

**Comment by m2en** [comment]
> > 現在においてのアーキテクチャ的な問題などによるリリースの支障ではないためP0を解除
> 
> @m2en 現状では非Windowsユーザー (例: ext4をデータパーティションとして使っているLinuxユーザー) が気をつければいいという話にとどまっているので`priority:Critical`は不適当だと考える。

Lowに引き下げた
