### ISSUE TITLE
discord.js v13.7.0 の小規模な破壊的変更への対応

### ISSUE THREAD

**Issue by mk-el** [approvers/OreOreBot2#188]
PR: #186 

### Corresponding Passage (該当箇所)

#186 のJest CIが落ちた箇所が対象です。

- `src/adaptor/discord-voice.ts` [step-4:10](https://github.com/approvers/OreOreBot2/runs/6428843305?check_suite_focus=true#step:4:10)
- `src/adaptor/discord-voice.ts` [step-4:38](https://github.com/approvers/OreOreBot2/runs/6428843305?check_suite_focus=true#step:4:38)
- `src/adaptor/discord-voice.ts` [step-4:66](https://github.com/approvers/OreOreBot2/runs/6428843305?check_suite_focus=true#step:4:66)

上記以外に `@discordjs/voice/dist/index.d.ts` のエラーがJestから報告されています。

[OreOreBot2 #315 - chore: bump discord.js from 13.6.0 to 13.7.0](https://github.com/approvers/OreOreBot2/runs/6428843305)

### Problem Analysis (問題の分析)

10時間前にリリースされた **discord.js v13.7.0** にて型に関する何かしらの変更が行われたことでOreOreBot2の既存の処理と v13.7.0で一致せず `TS2322` が発生しています。

どれもこのようなエラーが発生しています。

```
Type 'InternalDiscordGatewayAdapterCreator' is not assignable to type 'DiscordGatewayAdapterCreator'.
      Types of parameters 'methods' and 'methods' are incompatible.
```

### Problem Solution (問題の解決)

- [ ] `discord-voice.ts` に存在する型のエラーを修正し、テストが成功するようにする

### Additional Information (追加情報)

- [discordjs/discord.js - Releases v13.7.0](https://github.com/discordjs/discord.js/releases/tag/13.7.0)

**Comment by MikuroXina** [comment]
これは `discord.js` と `@discord/voice` で型が一致していないことによる問題なので, こちらにできることは無いでしょう. 修正を待つべきかと.

**Comment by mk-el** [comment]
#186 をクローズとしたのでこちらもクローズ
