### ISSUE TITLE
機能ラベルの自動付与

### ISSUE THREAD

**Issue by Meru92** [approvers/OreOreBot2#192]
### Problem Analysis (問題の分析)

- 現在それぞれの機能のラベルが手動で付与されているが、Auto Labeler で自動化する

**Comment by MikuroXina** [comment]
`auto-add-review-label.yml` のワークフローにて, *Resource not accessible by integration* というエラーになって動作していません

**Comment by MikuroXina** [comment]
また, 現状の規模だとラベル付けすることの恩恵が小さいと思います. これを実施する動機づけについて説明してほしいです. 必要性が無ければ単に取りやめてもよいかと

**Comment by Meru92** [comment]
@MikuroXina 

> auto-add-review-label.yml のワークフローにて稀に, `Resource not accessible by integration` というエラーになって動作していません

`Workflow permissions` の設定を `Read and write permissions` 解決するようです (一応)

参考: https://zenn.dev/tatsugon/articles/github-actions-permission-error

> また, 現状の規模だとラベル付けすることの恩恵が小さいと思います. これを実施する動機づけについて説明してほしいです. 必要性が無ければ単に取りやめてもよいかと

最初は **レビューが必要なpull request** / **Draft中のpull request** だということが明示的に示すことができればいいなと思っていたのでこのようなラベルやワークフローを作成していました。

ただ、さいなさんが言う **現状の規模だとラベル付けすることの恩恵が小さい** 
これは全くその通りだと思います。(規模がデカければこういうのいるだろうけど)

また actions list が大変なことになっていることも認知しました。
![image](https://user-images.githubusercontent.com/82575685/169994793-c541797a-289b-44e7-987a-b25328d70cdb.png)


必要性がなさそうなのでこの機にばっさり削除します。
