### ISSUE TITLE
feat: 特定ワードで一連のリアクション付ける機能

### ISSUE THREAD

**Issue by m2en** [approvers/OreOreBot2#285]
### Describe the solution you'd like (要望の内容)

限界開発鯖で動いているBot Ferris ( https://github.com/approvers/rusty-ponyo ) の **エイリアス機能** をインスパイアした機能を作成する

e.x - 1) `草` という発言 → 草の絵文字をリアクションとして送信する
e.x - 2) `留年` という発言 → "え？雪さん留年したの！？！？" をリアクションとして送信する

**Comment by MikuroXina** [comment]
かつてのはらちょに存在していた, 「響」が含まれるメッセージに専用の絵文字を返す機能をこちらで実現してもよいかと考えています.

**Comment by m2en** [comment]
> かつてのはらちょに存在していた, 「響」が含まれるメッセージに専用の絵文字を返す機能をこちらで実現してもよいかと考えています.
@MikuroXina 

よいとおもいます

**Comment by m2en** [comment]
done, #295
