### ISSUE TITLE
feat: メッセージデバック機能の追加

### ISSUE THREAD

**Issue by m2en** [approvers/OreOreBot2#312]
### Describe the solution you'd like (要望の内容)

#1 でMessageQuoteが開発するとの理由で除外されたメッセージデバック機能を追加

MessageQuoteでのデバック機能は仕様の関係で[削除されてしまった](https://github.com/m2en/MessageQuote/commit/3a8934847e2f0de1c879751fa9d6f13ceb2e3364)ため、今回のIssueを作成した。

機能としては `!debug <id>` を実行すると指定したIDのメッセージをコードブロック化して表示する
- [approvers/OreOreBot - message_debug.py](https://github.com/approvers/OreOreBot/blob/master/lib/message_debug.py)
- https://github.com/approvers/OreOreBot/pull/120

### Additional context (追加情報)

メッセージの取得は [`discord.js MessageManager#.fetch()`](https://discord.js.org/#/docs/main/stable/class/MessageManager?scrollTo=fetch) で出来るが、これはチャンネルを予め取得する必要がある。

実装の際は注意する必要がある。

(MessageQuoteはチャンネルIDがメッセージリンクにあったのでそのまま出来た)

**Comment by MikuroXina** [comment]
OreOreBot での実装は, コマンドを発行したチャンネルと同じチャンネル内のメッセージの ID にしか反応しないようになっています. こちらのほうがセキュアでありデバッグ目的としても理に適っていると思われます.

**Comment by m2en** [comment]
> OreOreBot での実装は, コマンドを発行したチャンネルと同じチャンネル内のメッセージの ID にしか反応しないようになっています. こちらのほうがセキュアでありデバッグ目的としても理に適っていると思われます.
@MikuroXina 

いいと思います
