### ISSUE TITLE
feat: 情報参照系のコマンドを追加する

### ISSUE THREAD

**Issue by m2en** [approvers/OreOreBot2#317]
### Describe the solution you'd like (要望の内容)

情報参照系のコマンドを追加

（作業を行うときは各タスクからissueを生成してから行ってください。）

- [x] #341
- アイコン
- ニックネーム (ユーザー名)
- ID
- 参加日時 (Discord Timestamp)
- ロール数 (ロールの種類は表示するとかわえもんとかのせいではらちょが壊れる)

- [x] #382
- [x] #353
- ロールカラー
- 作成日時 (Discord Timestamp)
- ロールアイコン
- ID
- そのロールを持つユーザー数
- ポジション (ロール配列の中の番号)

- [x] #338

**Comment by raiga0310** [comment]
ユーザ名からの逆引きあると検索しやすくないですか　数字以外が引数に入ればユーザ名からid変換とか

**Comment by MikuroXina** [comment]
:+1:. ただ数字のユーザ名の場合に困るので別コマンドになるかと

**Comment by m2en** [comment]
スラッシュコマンドだったら楽なんだが
