### ISSUE TITLE
`!userinfo <id>` - 指定したIDのユーザー情報を表示する(ギルドメンバーではない場合はエラーを返す) (Guild#GuildMember)

### ISSUE THREAD

**Issue by m2en** [approvers/OreOreBot2#341]
- アイコン

- ニックネーム (ユーザー名)

- ID

- 参加日時 (Discord Timestamp)

- ロール数 (ロールの種類は表示するとかわえもんとかのせいではらちょが壊れる)

**Comment by MikuroXina** [comment]
メンバーリストでのカテゴリ分けに用いられているロール (超スーパーガチプロ) や最も高い権限のロール (治安部隊など) も追加してはどうでしょうか?

**Comment by m2en** [comment]
Botだったら、その開発者を出すのもいいかも(そんなような話が出てた)

https://discord.com/channels/683939861539192860/891210643938611260/1003267185889779805
