### ISSUE TITLE
bug: difference-detectorのdiffが正確でない

### ISSUE THREAD

**Issue by Nanai10a** [approvers/OreOreBot2#372]
### Describe the bug (説明)

Discord上で以上の動作が認められました.

- 私がチャンネル `ch[1]` でメッセージ `msg[1]` を投稿する
- 私が `msg[1]` を編集し, `emsg[1]` へ変更する
- Botが `msg[1]` から `emsg[1]` へのdiff `diff[1 -> 1]` を `ch[1]` へ投稿する
- *...* (私, 他人が任意のチャンネルで任意のメッセージを投稿する, 編集は含まない)
- 私がチャンネル `ch[2]` でメッセージ `msg[2]` を投稿する
- 私が `msg[2]` を編集し, `emsg[2]` へ変更する
- Botが以下を同時に行う
  - `msg[2]` から `emsg[2]` へのdiff `diff[2 -> 2]` を `ch[2]` へ投稿する
  - `msg[2]` から **`emsg[1]`** へのdiff `diff[2 -> 1]` を **`ch[1]`** へ投稿する

### To Reproduce (再現方法)

再現性については検証していません.

### Expected behavior (期待される動作)

>  - `msg[2]` から **`emsg[1]`** へのdiff `diff[2 -> 1]` を **`ch[1]`** へ投稿する

この動作が起こらないこと.

### Screenshots (スクリーンショット)

`emsg[1]`

![image](https://user-images.githubusercontent.com/62282295/182537860-4230432b-a327-4153-bb04-667e51306943.png)

`emsg[2]`

![image](https://user-images.githubusercontent.com/62282295/182537907-4ea70a5b-36ec-4d36-b3be-0d782c472ca7.png)

`diff[2 -> 2]`

![image](https://user-images.githubusercontent.com/62282295/182537958-ccd4240e-f8fb-418d-80db-f6adc9afb166.png)

`diff[2 -> 1]`

![image](https://user-images.githubusercontent.com/62282295/182538030-3c1e8fc7-4ef3-4a61-ab43-963b5cda2ca7.png)

### Client Information (クライアント情報)

- OS: Linux archlinux 5.15.53-2-lts x86_64 GNU/Linux
- Client[e.g. Stable, Canary]: Browser (Firefox Developer Edition ver. 104.0b2)
- Version: stable 138734 (047115f)

### Additional context (追加情報)

無し.

**Comment by m2en** [comment]
発生バージョンは [`v1.21.0`](https://github.com/approvers/OreOreBot2/releases/tag/v1.21.0)

**Comment by MikuroXina** [comment]
挙動からして [`tuple.ts`](https://github.com/approvers/OreOreBot2/blob/5a856e221e55fdb3fc3941b3373bbb6f13718a5f/src/adaptor/proxy/transformer/tuple.ts) のバグのようです. 修正しておきます.
