### ISSUE TITLE
ci: ライセンスチェッカーの導入の提案

### ISSUE THREAD

**Issue by MikuroXina** [approvers/OreOreBot2#441]
### Problem Analysis (問題の分析)

#434 にて, ライセンス周りの問題によりマージできない事態が発生しました. 誤マージは済んでのところでストップできましたが, 今後もこのような事案が発生する可能性があります.

また, これまで使用してきた依存関係のライセンスが問題ないかどうかも検証できてない可能性があり, 自動で精査する仕組みが求められます.

### Problem Solution (問題の解決)

[こちらのライセンスチェッカー](https://github.com/guidesmiths/license-checker) を CI に組み込んで実行することを提案します. GPL ライセンスの依存関係を検知して弾けるはずです.

他にオンライン形式などのサービスもありますので, 更なるご提案などがあればコメントください.

**Comment by soshiharami** [comment]
とてもいいと思う
ライセンスチェッカー なるものがあるのを初めて知った

**Comment by m2en** [comment]
自分もいいと思います。人間は愚かで、特に僕はそれ以上に愚かなので、今後も多分調べずApproveしそうなので、CIで確認してもらえるとこちらとしても嬉しい
