### ISSUE TITLE
bug: Embed送信時にメッセージ更新イベントが発生し、Diffが送信されてしまう問題

### ISSUE THREAD

**Issue by m2en** [approvers/OreOreBot2#445]
### Describe the bug (説明)

Embedが送信されたときに `messageUpdate` イベントが発生しているのか編集指摘機能のDiff(見てたぞ)が発動してしまう

- はらちょのバージョン: `v1.21.0`

### To Reproduce (再現方法)

Embedを送信する

### Expected behavior (期待される動作)

Embedが送信されてもDiff(みてたぞ)が発生しない

### Screenshots (スクリーンショット)

![image](https://user-images.githubusercontent.com/82575685/188262225-3497cf81-0efe-450e-ab40-c4a305bf01d1.png)

### Client Information (クライアント情報)

- OS: Windows 11 Home Edition (64bit)
- Client[e.g. Stable, Canary]: Stable
- Version: Stable 145259 (5cd8da5)

**Comment by m2en** [comment]
#445 で暫定修正しています、 @kawaemon のThinkMonoホストから @m2en のUbuntuサーバーホストへ復旧したため、今後もこのエラーに関する監視を行います。

**Comment by MikuroXina** [comment]
1 週間経過しましたが同様の症状は再発していないため, Close します.
