### ISSUE TITLE
feat:  鯖名変更監視君

### ISSUE THREAD

**Issue by YukiYuigishi** [approvers/OreOreBot2#537]
### Describe the solution you'd like (要望の内容)
限界開発鯖のサーバー名が変更されたら公式Twitterによって告知する

**Comment by m2en** [comment]
公式Twitter..........?

**Comment by m2en** [comment]
> 公式Twitter..........?

@YukiYuigishi

**Comment by MikuroXina** [comment]
自動ツイートするのであればそういった方向の開発も必要になります. ボットアカウントを追加するのであればその管理やアダプタの開発なども必要なのでもう少し具体的な実装内容を決めてほしいです.
