### ISSUE TITLE
スラッシュコマンドへの移行

### ISSUE THREAD

**Issue by m1sk9** [approvers/OreOreBot2#560]
コマンド類を現行の **メッセージ方式** から **ApplicationCommand (Interaction API)方式** に移行する
@MikuroXina が #479 などでリファクタリングしたため移行はしやすいものの、後で後述する限界開発鯖における一連のInteraction API に追随する不具合により、移行しても鯖民全員が使えないもしくは一部の鯖民しか使えない問題が発生するため、移行は運営側で修正が入るまで [Discussions](https://github.com/approvers/OreOreBot2/discussions) などで会議するまでに留めたほうがいいと思われる (従来のメッセージ方式と共存させるならまた話が変わる

### Interaction API に追随する不具合

前述した該当不具合については `#無法地帯` でいくらか話が出たが以下のような不具合が発生している

- Slash CommandをサポートしているBotを導入してもSlash CommandがUI上に出現せず、利用できない (一部のメンバーは利用できる)
- Message Context Menuを該当ギルドに登録してもUI上に出現しない ~~(登録した本人は利用できる)~~ **正しくは登録した本人とギルドオーナー(ここではいっそう)は使える模様**
- サーバーメニューの Integrations に該当Botが出現しない (本来であれば出現するはず)

この不具合はすでにDiscord 運営の方に報告しているが、３ヶ月程全く話が進行していない

![image](https://user-images.githubusercontent.com/82575685/198880046-6f7218a9-d031-4fc8-ad49-0b0240b9ed33.png)

### Todo

- [ ] コマンド形態を決める
- [ ] 共存させるかの検討
- [ ] 移行作業

**Comment by m2en** [comment]
流石に6ヶ月無視されているのでもう一度何かアクションを起こすよう、Discord運営に連絡済み

**Comment by liliscats** [comment]
こんばんは。めるです。

今の限界開発鯖ではらちょが生きているかどうかすら怪しいんですが、メンテは続いているようなので一応コメントを残します。

----

> この不具合はすでにDiscord 運営の方に報告しているが、３ヶ月程全く話が進行していない

今なお返信は来ていません。また私はすでに限界開発鯖を脱退していて帰るかどうかも怪しいので私の方でチケットを閉じました。

私が脱退したあとにスラッシュコマンドが復活していればいいんですが、もし復活していないのであればギルドの所有者権限を持つ人 (この場合はいっそう) がチケットを作ったほうが多分解決は早いです。(もし、移行をしたいならの話です。移行しなくてもいいのであれば #560 の処遇はおまかせします。)

https://support.discord.com/hc/ja/requests/new?ticket_form_id=360000029212

**Comment by MikuroXina** [comment]
もはや対応しないことで Discord 公式に中指を立てていきたいので Close as not planned

**Comment by liliscats** [comment]
> もはや対応しないことで Discord 公式に中指を立てていきたいので Close as not planned

中指立てるの良いと思います、流石に1年放置はナメてる

もし帰ってこれたらはらちょ、触りたいのでみんな殺さないでね

**Comment by MikuroXina** [comment]
とりあえず実装は用意しておきます. 起動時の `FEATURE` オプションで有効化できるようにしておこうかと
