### ISSUE TITLE
CIの改善(クソデカ主語)

### ISSUE THREAD

**Issue by shun-shobon** [approvers/OreOreBot2#650]
### Corresponding Passage (該当箇所)

[この辺](https://github.com/approvers/OreOreBot2/tree/8cbe9cffc02155561eb9bc9c0dd532896281fdc3/.github/workflows)

### Problem Analysis (問題の分析)

現状のCIはNode.jsのセットアップが適切にされていなかったり、LockファイルをCI中に更新してしまう可能性があったり、使ってるActionのバージョンが古かったりと問題が多いので改善する必要があります。

### Problem Solution (問題の解決)

- [x] `setup-node`が使用されていない箇所への`setup-node`の追加
- [x] `yarn install`時に`yarn.lock`を更新しないように`--frozen-lockfile`オプションの追加
- [x] キャッシュの使用(`setup-node@3`以降であれば標準搭載されています)
- [x] 全体的なActionのバージョン更新
- [x] その他の改善

### Additional Information (追加情報)

多分 @m2en がやってくれる

**Comment by m2en** [comment]
シンガポールにいるので、日本に帰国したらやります

**Comment by shun-shobon** [comment]
@m2en 
嘘だったら許さないぞ ❤️
