### ISSUE TITLE
ヘルプコマンドのButtonに制限を設ける

### ISSUE THREAD

**Issue by m2en** [approvers/OreOreBot2#656]
`!help` で表示されるヘルプコマンドのページ送りに使用される Button は特に制限が設けられていないため、実行者以外がページ送りしたりすることができます。	

限界開発鯖のメンバーが Button を押しまくって Discord と めるのサーバー ( `dev.m2en.Ubuntu` ) と Vultr に迷惑をかけるのを止めるために以下の対策を行う

- [ ] `!help` を実行したメンバー以外のInteractionをブロックする
- [ ] 連続したInteractionをブロックする

**Comment by MikuroXina** [comment]
連続した Interaction に関しては Discord API の制約などもありますし, あまり気にすることではないかと.

コマンド実行者以外が触るタイプの機能も作れるようにしていましたが, ページを表示する関数の引数を `pages: EmbedPage[]` からオプション付きに変えて, ページ送りできるユーザーを変えられるかどうか指定できるオプションを追加する方向でどうでしょうか.

アダプタの該当箇所: https://github.com/approvers/OreOreBot2/blob/main/src/adaptor/proxy/command.ts#L135-L175
