### ISSUE TITLE
リリースプルリクエストのCIが動作しない

### ISSUE THREAD

**Issue by m1sk9** [approvers/OreOreBot2#690]
### バグレポートの提出を行う前に

- [X] すでに[同じバグを報告するIssue](https://github.com/approvers/OreOreBot2/issues?q=)が存在しないか確認しましたか?
- [X] セキュリティーに関する不具合ではありませんか? セキュリティーに関する不具合はIssueで報告せず[適切な方法](https://github.com/approvers/OreOreBot2/security/policy#reporting-a-vulnerability)で報告してください

### バグの詳細

- リリース準備ができると作成されるプルリクエストのCIが動作していない
- レビューを行っても動作していないので別の要因だと思う

![image](https://user-images.githubusercontent.com/82575685/214505002-2eceaed7-ef8f-4f4c-af54-a97c0365fb72.png)

### 再現方法

1. リリースプルリクエストを作成する - #688 
2. レビューをして approve する

### 期待する動作

以下のCIが動作する

- eslint
- prettier
- trivy

### はらちょのバージョン

```Text
-----
```

**Comment by m2en** [comment]
これは正直ブランチ保護をOFFにすれば解決する話なので、そこまで緊急性はないかもしれないが #701 を直したあとはこれに尽力したいところ

**Comment by m2en** [comment]
#688 見る感じ、大丈夫そう

**Comment by m2en** [comment]
改善が見られない。 #688 ではちゃんと動作してるんだけどな

**Comment by m1sk9** [comment]
動いてそう

![image](https://github.com/approvers/OreOreBot2/assets/82575685/2be92110-0709-4eb0-b0b5-543135450157)
