### ISSUE TITLE
trivy の脆弱性レポートが重複する

### ISSUE THREAD

**Issue by m1sk9** [approvers/OreOreBot2#702]
### バグレポートの提出を行う前に

- [X] すでに[同じバグを報告するIssue](https://github.com/approvers/OreOreBot2/issues?q=)が存在しないか確認しましたか?
- [X] セキュリティーに関する不具合ではありませんか? セキュリティーに関する不具合はIssueで報告せず[適切な方法](https://github.com/approvers/OreOreBot2/security/policy#reporting-a-vulnerability)で報告してください

### バグの詳細

trivy ci で security tab に通知される Docker イメージの脆弱性レポートが重複している

重複したレポートを見つけ次第 Dismiss しているが、重複しているレポートは作成されないようにする

### 再現方法

1. おそらくなんなかのプルリクエストを作成する
2. security tab を確認する

### 期待する動作

重複せず、レポートが正常に通知される

### はらちょのバージョン

```Text
v1.34.0
```

**Comment by m2en** [comment]
そもそも CI いるかという
はらちょに関係する CVE 出なさそうだしなぁと
