### ISSUE TITLE
限界開発鯖に初参加したメンバーを歓迎する機能を追加

### ISSUE THREAD

**Issue by m2en** [approvers/OreOreBot2#719]
### 機能要望の提出を行う前に

- [X] すでに[同じ機能要望を行うIssue](https://github.com/approvers/OreOreBot2/issues?q=)が存在しないか確認しましたか?
- [X] この要望を実現する保証はありません。よろしいですか?

### 要望の概要

限界開発鯖に初参加したメンバーを歓迎し、 [approvers/site](https://github.com/approvers/site) のメンバーリストにリンクを掲載していいかを問う機能を追加

- `assets/` 配下のコンフィグファイルで歓迎時に使用するメッセージフォーマットを変更できるようにする
- `#玄関` で ***†WELCOME TO UNDERGROUND†*** する
- `#無法地帯` で [approvers/site](https://github.com/approvers/site) のメンバーリストにリンクを掲載していいかを聞く (メンション付き)
   - 応答はリアクションのほうが望ましい

> 以下は例
> ```
> ***危険なコミュニティへようこそ***
> 限界開発鯖メンバーリストにTwitterやGitHubのリンクを掲載しても大丈夫ですか？(もちろん掲載なしでも大丈夫です )
> https://approvers.dev/member
> ```

### 代替え案

別Bot (またははらちょ) でメンバーリストへの追加まで自動化してしまうのもあり

https://discord.com/channels/683939861539192860/690909527461199922/1063381138548199434

**Comment by MikuroXina** [comment]
かなり実用的かつはらちょがダウンしていても新しい人が来た時に動作してほしいので, 別 Bot として実装することを検討したほうがよいかと思います

**Comment by m2en** [comment]
確かに、私がホストしている限り、多分難しい

ちょっと固めてから別Botで作ろう
