### ISSUE TITLE
chore: issueの存在確認でopenなissueに絞る

### ISSUE THREAD

**Issue by KisaragiEffective** [approvers/OreOreBot2#732]
### バグレポートの提出を行う前に

- [X] すでに[同じバグを報告するIssue](https://github.com/approvers/OreOreBot2/issues?q=)が存在しないか確認しましたか?
- [X] セキュリティーに関する不具合ではありませんか? セキュリティーに関する不具合はIssueで報告せず[適切な方法](https://github.com/approvers/OreOreBot2/security/policy#reporting-a-vulnerability)で報告してください

### バグの詳細

issueのテンプレートがopenなissue以外も出る

### 再現方法

1. バグ報告のテンプレートを使用
2. [同じバグを報告するIssue](https://github.com/approvers/OreOreBot2/issues?q=)をクリック

### 期待する動作

`is:open is:issue`に絞る

### はらちょのバージョン

```Text
1.37.0
```

**Comment by m2en** [comment]
#733 にある通り、意図的に削除したクエリのため , issue form の設定ファイル内コメントで記載 で対応
