### ISSUE TITLE
Docker 環境上で起動した際にクライアントバージョンが正しく取得できていない

### ISSUE THREAD

**Issue by m1sk9** [approvers/OreOreBot2#750]
### バグレポートの提出を行う前に

- [X] すでに[同じバグを報告するIssue](https://github.com/approvers/OreOreBot2/issues?q=)が存在しないか確認しましたか?
- [X] セキュリティーに関する不具合ではありませんか? セキュリティーに関する不具合はIssueで報告せず[適切な方法](https://github.com/approvers/OreOreBot2/security/policy#reporting-a-vulnerability)で報告してください

### バグの詳細

```shell
============

起動完了しました。

有効になっている機能> MESSAGE_CREATE, MESSAGE_UPDATE, COMMAND, VOICE_ROOM, ROLE, EMOJI

接続クライアント> OreOreBot2
接続クライアントID> 937234060282069003
接続クライアントバージョン> 不明

discord.js バージョン> 14.7.1

--------------------------------------------------
Core Dependencies
- @discordjs/voice: 0.14.0
- prism-media: 1.3.4

Opus Libraries
- @discordjs/opus: 0.9.0
- opusscript: not found

Encryption Libraries
- sodium-native: not found
- sodium: not found
- libsodium-wrappers: not found
- tweetnacl: 1.0.3

FFmpeg
- version: 5.1.2
- libopus: yes
--------------------------------------------------

============
```

起動時に本来表示されるバージョンが **不明** になっている

### 再現方法

1. Docker Imageをpullする
2. 起動する

### 期待する動作

正常にバージョンが表示される

### はらちょのバージョン

```Text
v1.39.0
```

**Comment by MikuroXina** [comment]
`version` コマンドは `package.json` から取得してきているので正常に動作しますが, エントリポイント側が `process.env.npm_package_version` を使っているせいのようです

該当箇所: https://github.com/approvers/OreOreBot2/blob/206cc9ef38960735f928695af14771bd7ae737a9/packages/bot/src/server/index.ts#L244
