### ISSUE TITLE
ブランチの運用を確定させる

### ISSUE THREAD

**Issue by merunno** [approvers/OreOreBot2#88]
- [x] ブランチの運用を決める
- [x] `CONTRIBUTING.md` でブランチの運用を記載する

**Comment by MikuroXina** [comment]
よくある運用をまとめておきます.

- 最新のメジャーバージョンの開発を `main` で行う.
- `main` からブランチを分岐して, 各機能の実装/修正を行い PR を作成する.
- バグ修正などをサポートしている過去のメジャーバージョンを `1.x.y` や `2.x.y` のようなブランチとして分け, そちらには `main` でのバグ修正コミットのみを取り入れる.

**Comment by merunno** [comment]
GitHub Flowとはまた違う?
