### ISSUE TITLE
スラッシュコマンドが自動更新されない

### ISSUE THREAD

**Issue by m1sk9** [approvers/OreOreBot2#976]
スラッシュコマンドの登録対象コマンドから各コマンドの alias を外したい. 登録数はかなり減ると思う。

スラッシュコマンドはメッセージコマンドと違いクライアントベースでコマンド補完があるので alias を用意する意味がない

**Comment by MikuroXina** [comment]
alias を登録から外したとしても, ミーム構文などの種類が多くそこまで登録数は減らないと思います. ミーム構文は引数のシステムが独自になっていてスラッシュコマンドの説明文も機能不全なので, ここの辺りを対策したほうが良さそうです.

また `population` などは人によって別名版の方しか覚えてない又はよく使っているということもありそうです.

**Comment by m1sk9** [comment]
> スラッシュコマンドが変わってても自動更新されないっていう仕様 (もしくはバグ) がある
> -- @m1sk9 

> コマンド登録処理で 100 行近くある上にテストが無いので, service/ に分けつつ単体テストを追加したいな
> -- @MikuroXina 

スラッシュコマンドが変わってても自動更新されないのでこの不具合を修正すべきだと考えた.
